package hibernate.model;
// Generated 23/08/2016 11:10:53 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbCareers generated by hbm2java
 */
public class TbCareers  implements java.io.Serializable {


     private Long flPkCareer;
     private String flNameCareer;
     private Set tbStudentses = new HashSet(0);

    public TbCareers() {
    }

	
    public TbCareers(String flNameCareer) {
        this.flNameCareer = flNameCareer;
    }
    public TbCareers(String flNameCareer, Set tbStudentses) {
       this.flNameCareer = flNameCareer;
       this.tbStudentses = tbStudentses;
    }
   
    public Long getFlPkCareer() {
        return this.flPkCareer;
    }
    
    public void setFlPkCareer(Long flPkCareer) {
        this.flPkCareer = flPkCareer;
    }
    public String getFlNameCareer() {
        return this.flNameCareer;
    }
    
    public void setFlNameCareer(String flNameCareer) {
        this.flNameCareer = flNameCareer;
    }
    public Set getTbStudentses() {
        return this.tbStudentses;
    }
    
    public void setTbStudentses(Set tbStudentses) {
        this.tbStudentses = tbStudentses;
    }

    @Override
    public String toString() {
        return "TbCareers{" + "flPkCareer=" + flPkCareer + ", flNameCareer=" + flNameCareer + ", tbStudentses=" + tbStudentses + '}';
    }




}


