package hibernate.model;
// Generated 23/08/2016 11:10:53 AM by Hibernate Tools 4.3.1



/**
 * TbStudents generated by hbm2java
 */
public class TbStudents  implements java.io.Serializable {


     private Long flPkRow;
     private TbCareers tbCareers;
     private String flEnrollment;
     private String flNameStudent;
     private String flLastNameStudent;
     private int flGender;

    public TbStudents() {
    }

	
    public TbStudents(String flEnrollment, String flNameStudent, String flLastNameStudent, int flGender) {
        this.flEnrollment = flEnrollment;
        this.flNameStudent = flNameStudent;
        this.flLastNameStudent = flLastNameStudent;
        this.flGender = flGender;
    }
    public TbStudents(TbCareers tbCareers, String flEnrollment, String flNameStudent, String flLastNameStudent, int flGender) {
       this.tbCareers = tbCareers;
       this.flEnrollment = flEnrollment;
       this.flNameStudent = flNameStudent;
       this.flLastNameStudent = flLastNameStudent;
       this.flGender = flGender;
    }
   
    public Long getFlPkRow() {
        return this.flPkRow;
    }
    
    public void setFlPkRow(Long flPkRow) {
        this.flPkRow = flPkRow;
    }
    public TbCareers getTbCareers() {
        return this.tbCareers;
    }
    
    public void setTbCareers(TbCareers tbCareers) {
        this.tbCareers = tbCareers;
    }
    public String getFlEnrollment() {
        return this.flEnrollment;
    }
    
    public void setFlEnrollment(String flEnrollment) {
        this.flEnrollment = flEnrollment;
    }
    public String getFlNameStudent() {
        return this.flNameStudent;
    }
    
    public void setFlNameStudent(String flNameStudent) {
        this.flNameStudent = flNameStudent;
    }
    public String getFlLastNameStudent() {
        return this.flLastNameStudent;
    }
    
    public void setFlLastNameStudent(String flLastNameStudent) {
        this.flLastNameStudent = flLastNameStudent;
    }
    public int getFlGender() {
        return this.flGender;
    }
    
    public void setFlGender(int flGender) {
        this.flGender = flGender;
    }




}


